src/CNTO.Launcher.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CNTO.Launcher.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


src/CNTO.Launcher.Web/Pages/Index.cshtml.cs
using CNTO.Launcher.Application;
using CNTO.Launcher.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CNTO.Launcher.Web.Pages;

[Authorize]
public class IndexModel : PageModel
{
    readonly AutoRestartService _autoRestartService;
    readonly LauncherService _launcherService;
    readonly IRepositoryCollection _repositoryCollection;
    readonly ILogger<IndexModel> _logger;

    public IndexModel(AutoRestartService autoRestartService,
                      LauncherService launcherService,
                      IRepositoryCollection repositoryCollection,
                      ILogger<IndexModel> logger)
    {
        _autoRestartService = autoRestartService;
        _launcherService = launcherService;
        _repositoryCollection = repositoryCollection;
        _logger = logger;
        Dlcs = new DlcCheckboxes();
    }

    [BindProperty]
    public DlcCheckboxes Dlcs { get; set; }

    public void OnGet()
    {

    }

    public async Task OnPostRestartAsync()
    {
        _logger.LogInformation("Restarting...");
        await _autoRestartService.RestartAsync();
    }

    public async Task OnPostStartAsync()
    {
        _logger.LogInformation("Starting main...");
        List<RepositoryId> repositoryIds = new();
        repositoryIds.Add(new("Main"));
        repositoryIds.Add(new("Server Only"));
        List<Dlc> startingDlcs = BuildDlcList();
        await _launcherService.StartServerAsync(repositoryIds, startingDlcs, 2);
    }

    private List<Dlc> BuildDlcList()
    {
        List<Dlc> startingDlcs = new();
        if (Dlcs.Vn) startingDlcs.Add(new("vn"));
        if (Dlcs.Gm) startingDlcs.Add(new("gm"));
        if (Dlcs.Csla) startingDlcs.Add(new("csla"));
        if (Dlcs.Ws) startingDlcs.Add(new("ws"));
        return startingDlcs;
    }

    public async Task OnPostStartCampaignAsync()
    {
        _logger.LogInformation("Starting campaign...");
        List<RepositoryId> repositoryIds = new();
        repositoryIds.Add(new("Main"));
        repositoryIds.Add(new("Campaign"));
        repositoryIds.Add(new("Server Only"));
        List<Dlc> startingDlcs = BuildDlcList();
        await _launcherService.StartServerAsync(repositoryIds, startingDlcs, 2);
    }

    public class DlcCheckboxes
    {
        public bool Vn { get; set; }
        public bool Gm { get; set; }
        public bool Csla { get; set; }
        public bool Ws { get; set; }
    }
}

src/CNTO.Launcher.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div>    
    <h2>Arma Server Launcher</h2>
    <form class="mt-2" method="post">
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="Dlcs.Vn" />
            <label class="form-check-label" for="Dlcs.Vn">Vietnam</label>
        </div>
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="Dlcs.Gm" />
            <label class="form-check-label" for="Dlcs.Gm">Global Mobilization</label>
        </div>        
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="Dlcs.Csla" />
            <label class="form-check-label" for="Dlcs.Csla">CSLA</label>
        </div>  
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="Dlcs.Ws" />
            <label class="form-check-label" for="Dlcs.Ws">Western Sahara</label>
        </div>          
        <input type="submit" class="btn btn-dark" value="Restart last" asp-page-handler="Restart" />
        <input type="submit" class="btn btn-dark" value="Main" asp-page-handler="Start" />
        <input type="submit" class="btn btn-dark" value="Campaign" asp-page-handler="StartCampaign" />
    </form>
</div>

src/CNTO.Launcher.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CNTO Luncher</title>
    <link rel="stylesheet" href="~/luncher/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/luncher/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CNTO Luncher</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/luncher/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/luncher/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/luncher/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>